### ISSUE TITLE
Add option of how to generate the view

### ISSUE THREAD

**Issue by mhenke** [raulriera/Scaffold#12]
Currently it uses cfform, add an option to use html tags like form. Would it be possible to have provide customization generation for the views.  Example, I have a site that looks like x and want to generate all the views instead of having to "fix" up all the view code.

**Comment by raulriera** [comment]
The current code used startFormTag() instead of cfform. About the templates, I guess you can always edit the files in the templates/ directory right? because adding something to "certain" form fields will be harder

**Comment by raulriera** [comment]
Or maybe I am not understanding this very well

**Comment by raulriera** [comment]
Commited to the repo
