### ISSUE TITLE
Ignore hidden folders in the templates/ directory

### ISSUE THREAD

**Issue by illuminerdi** [raulriera/Scaffold#14]
getTemplates() returns a query from a cfdirectory call on the templates/ folder. I have the plugin checked into SVN and this creates a .svn/ folder in that directory, which is getting sucked into the dropdown (and set as the default item, since it comes first) for template selection. It would probably be a good idea to either check to make sure the templates directories have the files that are needed to work, or just flat-out ignore 'hidden' folders, or some combination of both.

And yes, I'm sure I shouldn't be committing my plugins folders to SVN, but that comes later, and right now I'm scaffolding. :)

**Comment by netadvanced** [comment]
For anyone having the same issue, in the meantime, you could simply edit the index.cfm file and replace line 52 with something like that:
&lt;cfif type is &quot;DIR&quot; AND !reFind(&quot;&#94;.\w*&quot;,name)&gt;
This will skip any templates that start with a dot.

**Comment by raulriera** [comment]
Fixed! thanks netadvanced 43a86967e94226971ec3

**Comment by netadvanced** [comment]
Happy it helped. Thanks for your great plugin in the first place !
