### ISSUE TITLE
label tags in show and index views

### ISSUE THREAD

**Issue by mhenke** [raulriera/Scaffold#15]
I got asked about the label tag being in the views without input elements. 

Is it possible to remove the <label> tag when it doesn't defines a label for an input element in your generation templates?

http://www.w3schools.com/tags/tag_label.asp

**Comment by raulriera** [comment]
I don't understand what you are trying to tell me. What labels without input elements?

**Comment by mhenke** [comment]
"Isn't this kind of a funky use of < label >? Isn't < label > normally only used inside < form >?" was the actual quote.

Example show.cfm 
    <p><label>Entry I D</label> <br />

**Comment by raulriera** [comment]
A really old version of Scaffold used that (just as Rails) now it's just a textField (or any form helper) where you can adjust it using the labelPlacement and appendTo preppendTo properties.

Still unclear about the problem

**Comment by mhenke** [comment]
The problem is the scaffolding plugin is generating improper html.  Standards are to use a label with an input element.  Where is the input element belonging to the label on the show or index view? There isn't one, so there shouldn't be a label.

I wouldn't have caught this but the tech editor did for an article I am working on.

**Comment by raulriera** [comment]
Can you show me actual code? This is something in your form view helpers settings and not with Scaffold

**Comment by mhenke** [comment]
Maybe the scaffolding plugin is always passing in a label parameter I can't tell from the templates http://github.com/raulriera/Scaffold/blob/master/templates/default/views/index.cfm

Here is a sample show.cfm that was generated by the default template https://gist.github.com/5e041473e4df65c3ccee

**Comment by raulriera** [comment]
Nevermind.. I thought you meant the "entry forms" ... ok what should I use in the show instead of a label? what would be the correct html tag?

**Comment by mhenke** [comment]
that is a good question. maybe a span. these generated views are meant as a basic starting point not a highly, fancy solution. like this https://gist.github.com/5e041473e4df65c3ccee#gistcomment-7816

**Comment by raulriera** [comment]
Closed
