### ISSUE TITLE
includePartials for edit/new

### ISSUE THREAD

**Issue by joeydaly** [raulriera/Scaffold#16]
So far I keep repeating myself, each time I created a new scaffold object the first thing I do is create a "_form.cfm" partial, and put the input tags into it. Then just add #includePartial("form")# to edit.cfm and new.cfm -

I always create a table, and then add more columns - with partials it makes life easier just modifying the one file. Can this be implemented into Scaffold? since I use it soo much - let me know what you're thoughts are.

**Comment by raulriera** [comment]
Sadly no, I shouldn't be using any "dry up" logics to the templates (that can get confusing for newcomers, and I frankly most of my edit actions have less or more fields than the new)

I should implement easier to edit templates though... that could be a solution.

**Comment by joeydaly** [comment]
That's good enough for me!

**Comment by raulriera** [comment]
I will push something about this later today... 5:8am right now :)
