### ISSUE TITLE
Better flexibility to templates

### ISSUE THREAD

**Issue by raulriera** [raulriera/Scaffold#17]
So it would be easier to mix and match output preferences.

**Comment by chapmandu** [comment]
What did you have in mind here?

**Comment by raulriera** [comment]
I guess adding more options. Can't really remember :D I was mimicking an old version of Rails :D. BTW, do you want to be a collaborator? it's been ages since I used Scaffold

**Comment by chapmandu** [comment]
Yeah sure! I use it all the time.. and I have a few ideas.
