### ISSUE TITLE
Template dropdown is blank

### ISSUE THREAD

**Issue by joeydaly** [raulriera/Scaffold#20]
Using Fusegrid SDK with Wheels 1.1 RC 1 and H2 Database (the default one in Fusegrid)

Just installed the plugin and the template dropdown is blank. I checked the plugin folder, and all the templates are there.

I'll do some more testing and fiddling, may even upgrade it from 1.1 RC 1 to 1.1 see if that makes a difference.

**Comment by joeydaly** [comment]
Okay found the problem.

<cfif type is "DIR" AND !reFind("^.\w*",name)>

In issue #14 - this was added in to remove the .svn folder from being visible in the dropdown. Not sure why it's just rendering blank for me.

When I remove the refind and have just; <cfif type is "DIR"> it works.

**Comment by raulriera** [comment]
Hmmm I am going to revert that then.. thanks Joey :)

**Comment by joeydaly** [comment]
Yeah I spent a good 15 secs on trying to fix the regex, but I suck at regex. If I get bored later today I'll try have another crack.

**Comment by raulriera** [comment]
Removed :) will be updateing the zip at cfwheels in a few.. thanks
