### ISSUE TITLE
Re-Scaffold?

### ISSUE THREAD

**Issue by joeydaly** [raulriera/Scaffold#21]
Just creating a tennis app, and I seem to always be adding more tables or altering table columns I need to keep deleting my view folder for each model to add the new columns. I was wondering if it's possible to add a re-scaffold option, or make it by default that re-creates the view if it detects column changes in the model? Not sure how you'd do it... but just a suggestion.

**Comment by raulriera** [comment]
I think this was brought up before, I was thinking about adding a "overwrite" checkbox but that will overwrite everything not just a controller, views, etc... and making 3 seems like a bit overkill.

Depends on what is the amount of changes I would suggest either adding it manually (at the end it would most likely be a copy and paste of a textField function, or plan out more the data level with a plugin like DBMigrate)

**Comment by chapmandu** [comment]
Version 0.9 features an overwrite option
