### ISSUE TITLE
Generate model names as singular

### ISSUE THREAD

**Issue by chapmandu** [raulriera/Scaffold#28]
As per wheels convention. It would save much time manually renaming model files & modifying calls to models.

**Comment by tdm00** [comment]
Which version of the plugin are you using?

Right now when I use the scaffolding plugin it generates my model with a singular name and the Controller and View folder as plural.  So if I have create a table in my database named "contacts", then on the Scaffolding plugin I enter "contact" and the following are generated
controllers/Contacts.cfc
models/Contact.cfc
views/contacts/index.cfm

Is that not what you're getting?

**Comment by raulriera** [comment]
I don't understand the issue, the plugin follows the convention to the letter

**Comment by mhenke** [comment]
Maybe the wrong object name was typed in when generating? The wording is a little confusing but not much :-)

**Comment by chapmandu** [comment]
Sorry, my mistake. I have entered a plural model name thinking the database table name was expected.

Perhaps it would help if i read the hint:

Example: If your table is named "users", insert "user" in the form field below.

Classic case of RTFI.
