### ISSUE TITLE
plugin throws an error on helpers step

### ISSUE THREAD

**Issue by jja006** [raulriera/Scaffold#35]
The latest version (0.9) is throwing the following error when I try to scaffold anything.  This is on ACF 10, wheels 1.1.8, and Scaffold-0.9 (made from the zip from github):

[mypath...]/plugins/Scaffold/templates/default/tests/helpers.cfm (The system cannot find the file specified). 

To reproduce, just install the plugin, use it to scaffold for an object, leave all options selected/default, and choose the "cf9script" option (note, same results may occur with other template options - only had time to test w/cf9script selected.)

**Comment by chapmandu** [comment]
Do you get the same error using the default template?

**Comment by chapmandu** [comment]
Never mind, the helpers file is simply not there. Thanks for creating the ticket. In the meantime, just create an empty helpers.cfm file in that location.

**Comment by chapmandu** [comment]
helpers.cfm file created and included in test templates

**Comment by jja006** [comment]
Just to confirm - I finally had time today to update the plugin in my test project.  With the update it works fine in my environment and I get the expected output below.  Thanks!

output:
Generate form

Folder 'views/items/' and view files created.
File 'models/Item.cfc' created.
File 'controllers/Items.cfc' created.
File 'tests/unit/ItemTest.cfc' created.
File 'tests/functional/ItemsTest.cfc' created.
File 'tests/helpers.cfm' created.

Generate form

Folder 'views/collections/' and view files created.
File 'models/Collection.cfc' created.
File 'controllers/Collections.cfc' created.
File 'tests/unit/CollectionTest.cfc' created.
File 'tests/functional/CollectionsTest.cfc' created.
