### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by randy-johnson** [raulriera/Scaffold#5]
can't assign value to a Object of this type [Boolean] with key MESSAGE
Stacktrace   The Error Occurred in
 C:\www3\cfwheels\cfwheelstest\plugins\scaffold\Scaffold.cfc: line 15
13: 
14: 
15: <cfset loc.message = "">
16: 
17:

**Comment by raulriera** [comment]
What the... hehehe how did that get in there? fixed! thanks
