### ISSUE TITLE
Weird File Exists, but they don't

### ISSUE THREAD

**Issue by randy-johnson** [raulriera/Scaffold#8]
Generate form

File 'models/Comment.cfc' already exists so skipped.
Folder 'views/comments/' already exists so skipped.
File 'controllers/Comments.cfc' already exists so skipped.

I am getting this issue on my dev machine and my remote dev machine,   

I think what is happening is that the plugin see's another table I have in my DB that has the word comments in it like usercomments and it thinks that the files already exist.

Wheels 1.0  with latest version of Scaffold

**Comment by raulriera** [comment]
What value did you used to run the Scaffold? the plugin will take that value and do a "singularize" function to it.. so if you are doing the usercomments table then you should pass "usercomment"

**Comment by randy-johnson** [comment]
Yep  i typed in comment into the text field

**Comment by raulriera** [comment]
It only happens with "comment"? have you tried other tables? Maybe there is an error in my file movement and the files are being created outside of the wheelsapp? although this is all very strange :O

Funny thing is that I always test this over my comments table

**Comment by randy-johnson** [comment]
hmm  I will test it against another table and see what happens  I will create a markdowns table and then create a downs table and see what happens

**Comment by randy-johnson** [comment]
Hmm..  Slightly Different Results:

File 'models/Down.cfc' already exists so skipped.
Folder 'views/downs/' created.
File 'controllers/Downs.cfc' already exists so skipped.

The views folder was created, but it said the other two exist and they aren't there.

**Comment by raulriera** [comment]
Hmmm I will have to dig into this for a while then :) thanks for posting. I never tested it with those conditions..

**Comment by raulriera** [comment]
Tried to replicate, couldnt... will set to invalid for now

**Comment by randy-johnson** [comment]
ok,  if it happens again I will let you know.
Randy
